export function money(value: number) {
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function buildContent(title: string, lines: string[]) {
  const parts = ['BT', '/F1 18 Tf', '72 760 Td', `(${escapePdfText(title)}) Tj`, '/F1 11 Tf'];
  lines.forEach((line, index) => {
    parts.push(index === 0 ? '0 -28 Td' : '0 -18 Td');
    parts.push(`(${escapePdfText(line)}) Tj`);
  });
  parts.push('ET');
  return parts.join('\n');
}

export function createBoletoPdfBuffer(input: {
  clientName: string;
  clientDocument: string;
  amount: number;
  dueDate: string;
  boletoUrl?: string | null;
  linhaDigitavel?: string | null;
  codigoBarras?: string | null;
  pixUrl?: string | null;
}) {
  const lines = [
    `Client: ${input.clientName}`,
    `Document: ${input.clientDocument}`,
    `Amount: ${money(input.amount)}`,
    `Due date: ${input.dueDate}`,
    `Linha digitavel: ${input.linhaDigitavel ?? 'Not informed'}`,
    `Codigo de barras: ${input.codigoBarras ?? 'Not informed'}`,
    `Pix URL: ${input.pixUrl ?? 'Not informed'}`,
    `Boleto URL: ${input.boletoUrl ?? 'Not informed'}`,
    'Generated by Solara.',
  ];

  const content = buildContent('Boleto Solara', lines);
  const objects = [
    '%PDF-1.4\n',
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj\n',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n',
    `5 0 obj << /Length ${Buffer.byteLength(content, 'utf8')} >> stream\n${content}\nendstream endobj\n`,
  ];

  let offset = 0;
  const chunks: Buffer[] = [];
  const offsets: number[] = [0];

  for (const obj of objects) {
    const buf = Buffer.from(obj, 'utf8');
    chunks.push(buf);
    offset += buf.length;
    offsets.push(offset);
  }

  const xrefStart = offset;
  const xrefLines = [
    'xref\n',
    '0 6\n',
    '0000000000 65535 f \n',
    ...offsets.slice(1).map((off) => `${String(off).padStart(10, '0')} 00000 n \n`),
    'trailer << /Size 6 /Root 1 0 R >>\n',
    `startxref\n${xrefStart}\n%%EOF`,
  ].join('');

  chunks.push(Buffer.from(xrefLines, 'utf8'));
  return Buffer.concat(chunks);
}
